FROM node:18-alpine
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", ".eslintrc*", ".eslintignore*", "./"]
RUN npm install --development --silent && mv node_modules ../
COPY . .
EXPOSE 3000 9229
