version: "3.4"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - './data:/data/db'
    # ports:
    #  - 22222:27017
  nginx:
    image: nginx
    environment:
      PROXY_IP: http://signumlbri:3000/
    ports:
      - 800:80
      - 4430:443
    command: |
      sh -c "echo 'server {
        listen 80;
        server_name localhost;
        location / {
          proxy_pass http://signumlbri:3000;
          proxy_set_header Host \$$host;
          proxy_set_header X-Real-IP \$$remote_addr;
          proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto \$$scheme;
          proxy_read_timeout 90;
        }
      }' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
      # - /etc/letsencrypt/live/targi.zsel.opole.pl/fullchain.pem:/etc/nginx/ssl/cert.crt
      # - /etc/letsencrypt/live/targi.zsel.opole.pl/privkey.pem:/etc/nginx/ssl/cert.key
  signumlbri:
    image: signumlbri
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SESSION_SECRET: "A"
      MAIL_HOST:
      MAIL_USER:
      MAIL_SHOWMAIL:
      MAIL_PASSWORD:
      # NODE_ENV: production
      NODE_ENV: developement
      MONGODB_URI: mongodb://mongo:27017/
      MONGODB_URI_LOCAL: mongodb://mongo:27017/
    # ports:
    #   - 3000:3000
