@echo off
REM Force Docker rebuild and restart script for Windows
echo 🔄 Rebuilding SignumLBRI Enhanced container...
docker-compose build --no-cache signumlbri-enhanced
echo 🔄 Restarting container...
docker-compose up -d signumlbri-enhanced
echo 📋 Checking container logs...
docker-compose logs -f signumlbri-enhanced
